from models.client import Client
from models.seller import Seller
from models.concessionaire import Concessionaire
from models.service import Service
from models.equipment import Equipment
from models.extra_equipment import ExtraEquipment
from models.car import Car
from models.document import Document
from models.sale import Sale
from models.inventory import Inventory